name: Install cpanminus
description: Install cpanminus from web

runs:
  using: "composite"
  steps: 
    - run: curl -L -s -o cpanminus.pl https://cpanmin.us
      shell: bash
    - run: perl cpanminus.pl App::cpanminus local::lib
      shell: bash
    - run: rm -f cpanminus.pl
      shell: bash
    - run: |
        use lib '/home/runner/perl5/lib/perl5/';
        my @vars = qw(PERL_MB_OPT PERL_MM_OPT PERL5LIB PATH PERL_LOCAL_LIB_ROOT);

        my %old;
        @old{@vars} = @ENV{@vars};

        require local::lib;
        local::lib->import;

        for my $var (@vars) {
                next if !exists $ENV{$var};
                next if exists $old{$var} && $old{$var} eq $ENV{$var};

                print "::set-env ${var}::$ENV{$var}\n";
        }
      shell: perl -- {0}
