name: Install cpanminus
description: Install cpanminus from web

runs:
  using: "composite"
  steps: 
    - run: curl -L -s -o cpanminus.pl https://cpanmin.us
      shell: bash
    - run: perl cpanminus.pl App::cpanminus
      shell: bash
    - run: rm -f cpanminus.pl
      shell: bash
    - run: |
        my @vars = qw(PERL_MB_OPT PERL_MM_OPT PERL5LIB PATH PERL_LOCAL_LIB_ROOT);

        my %old;
        @old{@vars} = @ENV{@vars};

        require local::lib;
        local::lib->import;

        for my $var (@vars) {
                if ( exists $old{$var} ) {
                        if ( $old{$var} ne $ENV{$var} ) {
                                print "-->$ENV{$var}<--\n";
                        }
                }
                elsif ( exists $ENV{$var} ) {
                        print "==>$ENV{$var}<--\n";
                }
        }
      shell: perl -I ~/perl5/lib/perl5/ -- {0}
